#!/usr/bin/env python

import string

SOURCE = """
g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp. bmgle gr gl zw fylb gq glcddgagclr ylb rfyr'q ufw rfgq rcvr gq qm jmle. sqgle qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj.
"""
map_from = string.lowercase
map_to = string.lowercase[2:] + string.lowercase[:2]
translation = string.maketrans(map_from, map_to)


def convert(s):
    return string.translate(s, translation)

print convert(SOURCE)
print convert('map.html')
