#!/usr/bin/env python
import re
import requests

r = requests.get('http://www.pythonchallenge.com/pc/def/equality.html')
text = r.text.split('<!--')[1].split('-->')[0]

regex = re.compile('[^A-Z][A-Z]{3}([a-z])[A-Z]{3}[^A-Z]')
print ''.join(re.findall(regex, text))
